services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://hostname:5432/database_name
      - DATABASE_USERNAME=db_user
      - DATABASE_PASSWORD=db_password
