services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://dl-projects.postgres.database.azure.com:5432/hrms-java
      - DATABASE_USERNAME=dba
      - DATABASE_PASSWORD=yGyjBuKEMDj5ZA5
